### ISSUE TITLE
Decal legends positioned incorrectly

### ISSUE THREAD

**Issue by mjsadaway** [CQCumbers/kle_render#15]
Legends positioned correctly on keycaps are positioned incorrectly on decals.

![Decal Legend Test KLE](https://user-images.githubusercontent.com/42558043/96370490-fcf34780-112b-11eb-9705-9a56ce7857d8.png) is rendered as

![Decal Legend Test KLE-Render](https://user-images.githubusercontent.com/42558043/96370504-0b416380-112c-11eb-950d-7f3e147ce228.png)

JSON file is in [decal-legend-test.zip](https://github.com/CQCumbers/kle_render/files/5397627/decal-legend-test.zip).

**Comment by CQCumbers** [comment]
This should be fixed by https://github.com/CQCumbers/kle_render/commit/08ae013e731701dc6878ca271862a5fb8989d0ff, which no longer tries to automatically calculate the size of decals, and instead uses the user specified width and height This means decals that overflow their key boundaries are more likely to be cut off, but also makes it possible to manually address decal issues by resizing the key.
